### ISSUE TITLE
Extra Registration Fields not working with NUA

### ISSUE THREAD

**Issue by kuiperr005** [picklewagon/new-user-approve#12]
I have set some extra required registration fields like first_name and last_name in functions.php on the registration form. 

Problem: These extra fields are not validated, so a new user is always registered if he/she has filled in only the email adress and username. Do you have a solution for that?

Seems like the validation functions are called after the user is registrered for pending.

**Comment by picklewagon** [comment]
I don't have a solution for that. Since the plugin doesn't add those fields, it can't do any validation on that. I'm sure you could add some type of validation using core hooks.
