### ISSUE TITLE
MySQL server has gone away for query

### ISSUE THREAD

**Issue by Bjusters** [picklewagon/new-user-approve#28]
My error log are full of these lines for the

INSERT INTO `wp_options` (`option_name`, `option_value`, `autoload`) VALUES ('_transient_new_user_approve_user_statuses',

I only have 2000 members or something, shouldn`t be a problem right?

**Comment by picklewagon** [comment]
I'm looking into this issue. Sorry for the inconvenience.

**Comment by artuze** [comment]
I've noticed this potentially being the cause of some major slowdown issues with my site as well, site has over 7000 users. (wp-admin page loads are 15-20 seconds. DB doesn't seem to want to take a value that large)

One suggestion, and I haven't tested it yet, could be to rewrite the transient to store only the count of users for each status (that's primarily how that seems to be used, having just grepped for transient and get_user_statuses), and in the `admin-approve.php` file, just requery as needed. Maybe once in metabox_main, then split it and pass into user_table?

**Comment by artuze** [comment]
Another option I just had some success with – specify that the two uses of `WP_User_Query` in `_get_user_statuses` should only return the ID, user_login, and user_email fields, since those appear to be the only fields used in anywhere. A nice short fix, at the very least.

**Comment by picklewagon** [comment]
This has to do with the screen that is added by the plugin. The screen will be disabled in 1.8 although it will be possible to add it back in with a little code.

**Comment by picklewagon** [comment]
This has been resolved https://github.com/picklewagon/new-user-approve/releases/tag/1.7.5
