### ISSUE TITLE
User list filtering doesn't work

### ISSUE THREAD

**Issue by jrmain** [picklewagon/new-user-approve#42]
In the Wordpress All Users list, filtering the list by status (denied, approved, pending) doesn't seem to do anything at all.

**Comment by ChrisHardie** [comment]
See my Pull Request for an initial (non-JS) fix. The issue is discussed further in http://www.linsoftware.com/using-the-restrict_manage_users-action-hook-in-wordpress-4-4/ and http://wordpress.stackexchange.com/questions/213576/how-to-filter-users-on-admin-users-page-by-custom-meta-field

**Comment by jrmain** [comment]
Cool. I'm inclined to wait for your change to be folded into the official version, but I'd be willing to test it now if that would be helpful.
