### ISSUE TITLE
Admin-less new user approval using validation email.

### ISSUE THREAD

**Issue by sweisman** [picklewagon/new-user-approve#66]
I have the following use case.

1. New user registers.

2. Email is sent to new user with validation link.

3. New user clicks on link.

4. New user is approved.

I don't want any admin intervention into this process, as it's not needed. Does your plugin support this use case? How hard would it be to do?

**Comment by picklewagon** [comment]
The plugin does not support this use case. It would fall outside of the scope of what the New User Approve plugin actually does.
